//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sidebar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sidebar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiplomLayihe.AppCode.Resources.Admin.Sidebar.Sidebar", typeof(Sidebar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haqqımızda.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminlər.
        /// </summary>
        public static string Adminler {
            get {
                return ResourceManager.GetString("Adminler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azərbaycanca.
        /// </summary>
        public static string Azerbaijan {
            get {
                return ResourceManager.GetString("Azerbaijan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloq.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Post Şərhləri.
        /// </summary>
        public static string blogpostcomments {
            get {
                return ResourceManager.GetString("blogpostcomments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün İstifadəçilər.
        /// </summary>
        public static string Butun_Istifadechiler {
            get {
                return ResourceManager.GetString("Butun Istifadechiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimlə Əlaqə.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurslar.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dərs Cədvəli.
        /// </summary>
        public static string Ders_cedveli {
            get {
                return ResourceManager.GetString("Ders cedveli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dərslər.
        /// </summary>
        public static string Dersler {
            get {
                return ResourceManager.GetString("Dersler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektron Jurnal.
        /// </summary>
        public static string Elektron_Jurnal {
            get {
                return ResourceManager.GetString("Elektron Jurnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngiliscə.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtarış edin.
        /// </summary>
        public static string Enter_keywords {
            get {
                return ResourceManager.GetString("Enter keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivlik.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivlik Qalereyyası.
        /// </summary>
        public static string Event_Gallery {
            get {
                return ResourceManager.GetString("Event Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivlik Danışmacıları.
        /// </summary>
        public static string Event_Speakers {
            get {
                return ResourceManager.GetString("Event Speakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fənn.
        /// </summary>
        public static string Fenn {
            get {
                return ResourceManager.GetString("Fenn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əsas Səhifə.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmtahan Cədvəli.
        /// </summary>
        public static string Imtahan_cedveli {
            get {
                return ResourceManager.GetString("Imtahan cedveli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmtahanlar.
        /// </summary>
        public static string Imtahanlar {
            get {
                return ResourceManager.GetString("Imtahanlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İxtisas.
        /// </summary>
        public static string İxtisas {
            get {
                return ResourceManager.GetString("İxtisas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İxtisaslar.
        /// </summary>
        public static string Ixtisaslar {
            get {
                return ResourceManager.GetString("Ixtisaslar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Xəbərlər və Aktivliklər.
        /// </summary>
        public static string Last_News_And_Events {
            get {
                return ResourceManager.GetString("Last News And Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıxış.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajlar.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllim.
        /// </summary>
        public static string Muellim {
            get {
                return ResourceManager.GetString("Muellim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllimlər.
        /// </summary>
        public static string Muellimler {
            get {
                return ResourceManager.GetString("Muellimler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ziyarətçi.
        /// </summary>
        public static string New_Visitor {
            get {
                return ResourceManager.GetString("New Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köhnə Ziyarətçi.
        /// </summary>
        public static string Old_Visitor {
            get {
                return ResourceManager.GetString("Old Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan və Qiymətlər.
        /// </summary>
        public static string Plan_And_Pricing {
            get {
                return ResourceManager.GetString("Plan And Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Açıqlamaları.
        /// </summary>
        public static string Plan_Explanation {
            get {
                return ResourceManager.GetString("Plan Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qəbul ili.
        /// </summary>
        public static string Qebul_ili {
            get {
                return ResourceManager.GetString("Qebul ili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qrup.
        /// </summary>
        public static string Qrup {
            get {
                return ResourceManager.GetString("Qrup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qruplar.
        /// </summary>
        public static string Qruplar {
            get {
                return ResourceManager.GetString("Qruplar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rusca.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrlər.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil ol.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayt Ziyarəti.
        /// </summary>
        public static string Site_Traffic {
            get {
                return ResourceManager.GetString("Site Traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muellimler(sayt ucun).
        /// </summary>
        public static string Teachers_for_site_ {
            get {
                return ResourceManager.GetString("Teachers(for site)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tədris Fənnləri.
        /// </summary>
        public static string Tedris_Fennleri {
            get {
                return ResourceManager.GetString("Tedris Fennleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tələbə.
        /// </summary>
        public static string Telebe {
            get {
                return ResourceManager.GetString("Telebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tələbələr.
        /// </summary>
        public static string Tələbələr {
            get {
                return ResourceManager.GetString("Tələbələr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün Sifarişlər.
        /// </summary>
        public static string Total_Orders {
            get {
                return ResourceManager.GetString("Total Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ümumi Gəlir.
        /// </summary>
        public static string Total_Revenue {
            get {
                return ResourceManager.GetString("Total Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçilər.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziyarətçilər.
        /// </summary>
        public static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xəbərlər.
        /// </summary>
        public static string Xeberler {
            get {
                return ResourceManager.GetString("Xeberler", resourceCulture);
            }
        }
    }
}
